<a href="https://colab.research.google.com/github/shanchiyu-ntu/Kikuch-SLE/blob/master/source.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
# Reading data
from google.colab import files
file=files.upload()
dataset=pd.read_csv('C4d2.csv')

Saving C4d2.csv to C4d2.csv


**Data preprocessing**
 Missing data, Normalization, Splitting training and test dataset

In [0]:
# Preprocessing for missing data
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='most_frequent')
imp.fit(dataset)
dataset_imp= imp.transform(dataset)
dataset_imp=pd.DataFrame(dataset_imp)

In [0]:
# y: diagnosis (1: KD, 21: LL) # X: clinical, histologic, and C4d IHC results
y = dataset_imp.iloc[:,0].values
X= dataset_imp.iloc[:,1:-1].values

In [0]:
# Normalization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X)
X = sc.transform(X)

In [0]:
# Development cohort (X_train, y_train); Validation cohort (X_test, y_test)
y_train=y[0:100,]
y_test=y[100:,]
X_train=X[0:100,]
X_test=X[100:,]

**Training models:**
  Liner SVC,  SVM,   Random Forest

In [0]:
# Linear SVC model training
from sklearn.svm import LinearSVC 
classifier = LinearSVC()
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [0]:
print ("linear SVC model")
prediction= classifier.predict (X_test)
print ("The prediction is:")
print (prediction)
print ("The answer is:")
print (y_test)

# Caculate True positive, False positive, True negative, False negative in the Development cohort and validation cohort respectively
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, classifier.predict(X_test))
print ("In the validation cohort:")
print (cm)
print ("In the development cohort:")
cm2=confusion_matrix(y_train,classifier.predict(X_train))
print (cm2)


linear SVC model
The prediction is:
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 21.  1.  1.
 21.  1.  1.  1.  1.  1.  1. 21.  1. 21. 21.  1. 21.  1.  1.  1. 21.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.]
The answer is:
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 21.  1.  1.  1.  1.  1.  1. 21.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.]
In the validation cohort:
[[49  6]
 [ 1  1]]
In the development cohort:
[[81  0]
 [ 0 19]]


In [0]:
#SVC (kernal=linear) model training
from sklearn import svm
clf=svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
prediction= clf.predict (X_test)
print ("SVM model (kernel=linear)")
print ("The prediction is:")
print (prediction)
print ("The answer is:")
print (y_test)

# Caculate True positive, False positive, True negative, False negative in the Development cohort and validation cohort respectively
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, clf.predict(X_test))
print ("In the validation cohort:")
print (cm)
print ("In the development cohort:")
cm2=confusion_matrix(y_train,clf.predict(X_train))
print (cm2)

SVM model (kernel=linear)
The prediction is:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The answer is:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1.]
In the validation cohort:
[[54  1]
 [ 2  0]]
In the development cohort:
[[80  1]
 [ 0 19]]


In [0]:
#SVC (kernal=sigmoid) model training
from sklearn import svm
clf3=svm.SVC(kernel='sigmoid')
clf3.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
prediction= clf3.predict (X_test)
print ("SVM model (kernel=sigmoid)")
print ("The prediction is:")
print (prediction)
print ("The answer is:")
print (y_test)

# Caculate True positive, False positive, True negative, False negative in the Development cohort and validation cohort respectively
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, clf3.predict(X_test))
print ("In the validation cohort:")
print (cm)
print ("In the development cohort:")
cm2=confusion_matrix(y_train,clf3.predict(X_train))
print (cm2)

SVM model (kernel=sigmoid)
The prediction is:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 2. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The answer is:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1.]
In the validation cohort:
[[53  2]
 [ 0  2]]
In the development cohort:
[[78  3]
 [ 5 14]]


In [0]:
# Randome Forest model training
from sklearn.ensemble import RandomForestClassifier 
clf2= RandomForestClassifier()
clf2.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
prediction= clf2.predict (X_test)
print ("Random Forest model")
print ("The prediction is:")
print (prediction)
print ("The answer is:")
print (y_test)

# Caculate True positive, False positive, True negative, False negative in the Development cohort and validation cohort respectively
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, clf2.predict(X_test))
print ("In the validation cohort:")
print (cm)
print ("In the development cohort:")
cm2=confusion_matrix(y_train,clf2.predict(X_train))
print (cm2)

Random Forest model
The prediction is:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The answer is:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1.]
In the validation cohort:
[[53  2]
 [ 1  1]]
In the development cohort:
[[80  1]
 [ 2 17]]


In [0]:
# Save the models
from sklearn.externals import joblib
joblib.dump(classifier, 'linearSVC.pkl')
joblib.dump(clf, 'SVMlinear.pkl')
joblib.dump(clf3, 'SVMsigmoid.pkl')
joblib.dump(clf2, 'randomforest.pkl')

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['randomforest.pkl']

**Use the pretrained model**
Upload the parameters as a csv file. Total 33 columns: Diagnosis, plus 32 parameters (Missing data is allowed)

In [0]:
# Load the pretrained model
filename='SVMsigmoid.pkl'
#filename='linearSVC.pkl'
#filename='SVMlinear.pkl'
#filename='randomforest.pkl'
loaded_model = joblib.load(filename)


# Upload the unknown case as unknown case.csv (32 parameters for each case)
from google.colab import files
file=files.upload()
newdataset=pd.read_csv('unknown cases.csv')

Saving unknown cases.csv to unknown cases.csv


In [0]:
# Preprocess as the training dataset
newdataset_imp= imp.transform(newdataset)
newdataset_imp=pd.DataFrame(newdataset_imp)
X_new= newdataset_imp.iloc[:,1:-1].values
X_new_imp=pd.DataFrame(X_new)
X_new_scaled = sc.transform(X_new_imp)

# Prediction
result = loaded_model.predict(X_new_scaled)
print ("The prediction is:")
print (result)

The prediction is:
[2. 2. 2. 2. 1. 2. 1. 2. 1. 2. 2. 2. 1. 1. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
